# List comprehension and numpy

## Name: Minh Le

### Part 1: List comprehension, list indexing
First, read the tutorial at: https://www.programiz.com/python-programming/list-comprehension

Take the following list, below, and use list comprehension to complete the following. You must use list comprehension, and you mmust start with the original list (startList) each time. 

(a) Create a new list from every other element, starting at index 0

(b) Create a new list that contains True for each element in the original list that is even, False if it is odd

(c) Create a new list that replaces the values in the original list with 1, 2 or 3 under the following conditions. If the value is less than 3, make the new value 1, if it's greater than or equal to 3. but below 6, make it equal to 2, otherwise make it 3

(d) Use slicing to make a shallow copy of the complete list. To test, change one element of your new list, and print both lists. Make sure ONLY your new list changes (because lists are pass-by-reference)

(e) Go through the list of lists contained in the variable data, and extract all elements from each list EXCEPT the last one, and put into a new list of lists. You must use list comprehension.

e.g. the output should be: [[1, 2], [4, 5], [7, 8], [10, 11]]

(f) Go through the list of lists contained in the variable data, and create a single list containing ONLY the last element of each nested list. You must use list comprehension.

e.g. the output should be: [3, 6, 9, 12]

In [17]:
# Use this list for a-d above

startList = [2, 7, 1, 9, 1, 4, 8, 10, 2, 3, 5]

#a
elemList = list([x] for x in startList)

#b
oddEven = list(True if x % 2 == 0 else False for x in startList)

#c
replaceList = list(1 if x<3 else 2 if x>=3 and x < 6 else 3 for x in startList)

#d
shallowCopy = [x for x in startList]

# Use this list for e-f above

data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

#e
newList = [[row[i], row[i+1]] for row in data for i in range(1)]

#f
smallList = [nestedList[len(nestedList)-1] for nestedList in data]


#Test
print("Test a:", elemList == [[2], [7], [1], [9], [1], [4], [8], [10], [2], [3], [5]])

print("Test b:", oddEven == [True, False, False, False, False, True, True, True, True, False, False])

print("Test c:", replaceList == [1, 3, 1, 3, 1, 2, 3, 3, 1, 2, 2], "\n")

print("Test d:")
print("Initial copy:", shallowCopy)
shallowCopy[2] = 100
print("Copy after change:", shallowCopy)
print("Original list doesn't change:", startList, "\n")

print("Test e:", newList == [[1, 2], [4, 5], [7, 8], [10, 11]])

#f
print("Test f:", smallList == [3, 6, 9, 12])

Test a: True
Test b: True
Test c: True 

Test d:
Initial copy: [2, 7, 1, 9, 1, 4, 8, 10, 2, 3, 5]
Copy after change: [2, 7, 100, 9, 1, 4, 8, 10, 2, 3, 5]
Original list doesn't change: [2, 7, 1, 9, 1, 4, 8, 10, 2, 3, 5] 

Test e: True
Test f: True


### Part 2: Multiple return values

Read the tutorial at: https://www.tutorialspoint.com/How-do-we-return-multiple-values-in-Python

(a) Write a function called minmax, that takes a list as a single argument, and returns two values as a tuple - the minimum value in the list, and the maximum value in a list. 

(b) Use the random.randint(a,b) function to create a list filled with 100 random integers in the range 0 to 100 (inclusive).

(c) Pass this list to your function from (a), capture the two return values into TWO distinct variables, and print them nicely! (i.e. Print two, distinct, meaningful output messages, not just the tuple returned).

In [1]:
import random

#a
def minMax(inputList):
    minVal = min(inputList)
    maxVal = max(inputList)
    return minVal, maxVal

#b
i = 0
newList = []
while i < 100:
    newList.append(random.randint(0,100))
    i = i + 1
print("List with 100 random values between 0 and 100:", newList)

#c
tupleVal = minMax(newList)
print("Minimum value", tupleVal[0])
print("Maximum value", tupleVal[1])

List with 100 random values between 0 and 100: [41, 82, 52, 6, 73, 59, 24, 92, 51, 83, 73, 53, 71, 52, 89, 31, 0, 60, 60, 17, 16, 58, 36, 25, 10, 78, 50, 28, 84, 61, 22, 100, 34, 1, 67, 12, 93, 40, 7, 17, 93, 50, 58, 78, 88, 99, 35, 1, 76, 91, 75, 21, 97, 36, 56, 89, 78, 21, 20, 41, 53, 28, 44, 25, 92, 12, 71, 52, 61, 66, 29, 90, 45, 56, 89, 80, 21, 58, 53, 96, 36, 4, 12, 48, 45, 9, 13, 85, 33, 68, 76, 18, 55, 15, 54, 21, 22, 25, 15, 74]
Minimum value 0
Maximum value 100


### Part 3: Numpy

Read the tutorial at: https://machinelearningmastery.com/index-slice-reshape-numpy-arrays-machine-learning-python/
You may also want to check the following for information on array indexing in more detail: https://www.tutorialspoint.com/numpy/numpy_indexing_and_slicing.htm

Then work on the following:

(a) convert the startList to a one dimensional array. Print this array, and it's shape. Nicely.

(b) convert the startList into a two dimensional array, of 4 rows of 3 columns. Print this array, and it's shape. Nicely.

(c) use array slicing on (b) to produce similar output to 1(e) and 1(f) above. One variable containing 4 rows of 2 columns (all the data EXCEPT the last column from each row), and one variable that is a 4 by 1 array, containing the values from the last column. You will need to reshape this last variable (so a (4,) shape is not acceptable, but a (4,1) is). 

In [54]:
import numpy as np
from numpy import array
from numpy import reshape

startList = [12,26,18,1,15,18,12,19,2,7,4,9]

#a
oneD = array(startList)
print("One dimensional array:", oneD)
print("One dimensional array's shape:", oneD.shape, "\n")

#b
twoD = oneD.reshape((4, 3))
print("Two dimensional array: \n", twoD)
print("Two dimensional array's shape:", twoD.shape, "\n")

#c
newList = twoD[:,:-1]
print("List excluding the last item of each nested list: \n", newList)
print("List's shape:", newList.shape, "\n")


lastItem = twoD[:, -1]
lastItem = lastItem.reshape((lastItem.shape[0],1))
print("List with only the last item of each nested list: \n", lastItem)
print("List's shape:", lastItem.shape, "\n")

One dimensional array: [12 26 18  1 15 18 12 19  2  7  4  9]
One dimensional array's shape: (12,) 

Two dimensional array: 
 [[12 26 18]
 [ 1 15 18]
 [12 19  2]
 [ 7  4  9]]
Two dimensional array's shape: (4, 3) 

List excluding the last item of each nested list: 
 [[12 26]
 [ 1 15]
 [12 19]
 [ 7  4]]
List's shape: (4, 2) 

List with only the last item of each nested list: 
 [[18]
 [18]
 [ 2]
 [ 9]]
List's shape: (4, 1) 

